"""Search our own trajectories for one that transfers well to unseen boards.

    .venv/bin/python search.py <n_routes> <n_eval> [--agent=main.py]

The leaders freeze a 720-turn route and replay it. Measured in FINDINGS 39-41,
that works because the farm is a deterministic grid, and it is not a property of
their agent -- our own routes transfer too (53%-162% of home over ten unseen
seeds, and a frozen route goes 5-5 against our live agent).

So freezing costs nothing and gains nothing by itself. The whole payoff is in
*which* route gets frozen, and that is a search: our live agent averages about
82k but its best boards clear 130k, so the tail is what is being fished for. A
route is generated by letting the agent play a seed, and scored by replaying it
against the live agent on a fixed set of held-out seeds it has never seen.

Ranks on the median MARGIN over the live agent, not on the route's own score.
The live agent plays against the route, so its score is not a fixed baseline --
a route that produces 107k may also leave the agent 108k. The first version of
this ranked on absolute held-out score and promoted routes that lose 2 of 6
above routes that win 4 of 6. Median rather than mean because the transfer
distribution has long tails both ways (53% of home on one board, 162% on
another) and a mean promotes a route carried by one lucky seed.

Home score is not a filter and must not become one: the best home score in the
first search (133,178) had the worst held-out median (66,594) and lost 0 of 6.
Strength on a route's own board is a different property from transferable
strength.
"""
import json
import os
import statistics as st
import sys

import route
import transfer

SCRATCH = "/tmp/kagg-routes"


def evaluate(path, agent, seeds):
    scores = []
    for s in seeds:
        _, _, away, us = transfer.run(path, f"seed:{s}", agent)
        scores.append((away, us))
    return scores


if __name__ == "__main__":
    n_routes = int(sys.argv[1]) if len(sys.argv) > 1 else 20
    n_eval = int(sys.argv[2]) if len(sys.argv) > 2 else 6
    agent_path = next((a.split("=", 1)[1] for a in sys.argv[1:]
                       if a.startswith("--agent=")), "main.py")
    os.makedirs(SCRATCH, exist_ok=True)
    m = route.load(agent_path)
    opp = route.load(agent_path)

    # Held-out boards, fixed for every route so the ranking is paired, and
    # disjoint from the seeds routes are generated on.
    eval_seeds = list(range(7000, 7000 + n_eval))
    gen_seeds = list(range(6100, 6100 + n_routes))

    print(f"generating {n_routes} routes, scoring each on {n_eval} held-out seeds")
    print(f"{'route':>8}{'home':>10}{'medmargin':>10}{'meanmarg':>10}{'worst':>10}{'wins':>7}")
    rows = []
    for gs in gen_seeds:
        path = f"{SCRATCH}/route-{gs}.json"
        if not os.path.exists(path):
            replay, rewards = route.record(gs, m.agent, opp.agent)
            for turn in replay["steps"]:
                turn[1] = dict(turn[0])
            json.dump(replay, open(path, "w"))
            home = rewards[0]
        else:
            home = json.load(open(path))["steps"][-1][0].get("reward", 0)
        sc = evaluate(path, m.agent, eval_seeds)
        margins = [a - u for a, u in sc]
        wins = sum(1 for x in margins if x > 0)
        rows.append((st.median(margins), st.mean(margins), min(margins), wins, gs, home))
        print(f"{gs:>8}{home:>10,.0f}{st.median(margins):>+10,.0f}"
              f"{st.mean(margins):>+10,.0f}{min(margins):>+10,.0f}"
              f"{wins:>4}/{n_eval}", flush=True)
    rows.sort(reverse=True)
    print("\nbest by median margin over the live agent:")
    for med, mean, worst, wins, gs, home in rows[:6]:
        print(f"  seed {gs}  median {med:+,.0f}  mean {mean:+,.0f}  worst {worst:+,.0f}  "
              f"wins {wins}/{n_eval}  ({SCRATCH}/route-{gs}.json)")
